const repository = process.env.GITHUB_REPOSITORY || "facuscholze/I-m-Facundo-Scholze";
const [repositoryOwner, repositoryName] = repository.split("/");
const isUserOrOrganizationPage =
  repositoryName?.toLowerCase() === `${repositoryOwner?.toLowerCase()}.github.io`;

const normalizeBasePath = (path) => {
  if (!path || path === "/") return "";
  return `/${path.replace(/^\/+|\/+$/g, "")}`;
};

// GitHub Actions automatically builds project sites under /<repository-name>.
// Set NEXT_PUBLIC_BASE_PATH explicitly to override this (use an empty value for a root site).
const basePath =
  process.env.NEXT_PUBLIC_BASE_PATH !== undefined
    ? normalizeBasePath(process.env.NEXT_PUBLIC_BASE_PATH)
    : process.env.GITHUB_ACTIONS === "true" && !isUserOrOrganizationPage
      ? `/${repositoryName}`
      : "";

/** @type {import('next').NextConfig} */
const nextConfig = {
  // A fully static `out/` directory is generated by `next build` for GitHub Pages.
  output: "export",
  trailingSlash: true,
  basePath,
  assetPrefix: basePath ? `${basePath}/` : undefined,
  // Public assets and next/image are safe for a static export (no image optimizer server needed).
  images: {
    unoptimized: true,
  },
  // Make the selected base path available to links that point into /public.
  env: {
    NEXT_PUBLIC_BASE_PATH: basePath,
  },
  // The live preview is served from an e2b.app subdomain in Arena.
  allowedDevOrigins: ["*.e2b.app"],
  reactStrictMode: true,
};

module.exports = nextConfig;
